version: '3'

services:
  backend:
    build: ./mediaverse_Backend
    command: gunicorn --bind 0.0.0.0:8000 app_mediaverse.wsgi:application
    volumes:
      - ./mediaverse_Backend/app_mediaverse:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:#IRP#mediaverse@db:5432/mediaverse_db

  migrate:
    build: ./mediaverse_Backend
    command: ["sh", "-c", "python manage.py migrate"]
    volumes:
      - ./mediaverse_Backend/app_mediaverse:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:#IRP#mediaverse@db:5432/mediaverse_db


  frontend:
    build: ./Mediaverse_Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: 'mediaverse_db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '#IRP#mediaverse'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_USERNAME: 'admin'
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin123'
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
